Repository RawTherapee/RawTherapee, pull requests merged in 2018-03, with the labels that each got.

#4413 Speedup for rcd demosaic
  rtengine/CMakeLists.txt
  rtengine/demosaic_algos.cc
  rtengine/rcd_demosaic.cc
  rtengine/simpleprocess.cc
Labels: Performance, raw

#4406 review of 'rtengine/PF_correct_RT.cc'
  rtengine/PF_correct_RT.cc
  rtengine/demosaic_algos.cc
  rtengine/improcfun.cc
  rtengine/improcfun.h
  rtengine/jaggedarray.h
  rtengine/procparams.h
  rtengine/settings.h
  rtengine/shmap.cc
  rtengine/sleefsseavx.c
  rtgui/dirpyrequalizer.cc
  rtgui/options.cc
Labels: Performance, enhancement

#4442 Speedup for sony_arq_load_raw()
  rtengine/dcraw.cc
Labels: Performance, raw

#4461 added possibility to specify extra working spaces via a json file
  rtengine/clutstore.cc
  rtengine/dcp.cc
  rtengine/iccstore.cc
  rtengine/iccstore.h
  rtengine/rawimagesource.cc
  rtengine/rt_math.h
  rtgui/icmpanel.cc
Labels: color management, docs, enhancement

#4459 feature: added option to use a (fast) neutral RAW rendering in 'inspector mode'
  rtdata/languages/default
  rtengine/rawimagesource.cc
  rtengine/rawimagesource.h
  rtengine/rtthumbnail.cc
  rtengine/settings.h
  rtgui/inspector.cc
  rtgui/inspector.h
  rtgui/options.cc
  rtgui/options.h
  rtgui/preferences.cc
  rtgui/preferences.h
Labels: docs, enhancement
