Repository RawTherapee/RawTherapee, pull requests merged in 2022-08, with the labels that each got.

#6553 Add several DCPs
  rtdata/dcpprofiles/Canon EOS 5D Mark II.dcp
  rtdata/dcpprofiles/Canon EOS-1D X Mark III.dcp
  rtdata/dcpprofiles/Canon EOS-1Ds Mark II.dcp
  rtdata/dcpprofiles/FUJIFILM X-T4.dcp
  rtdata/dcpprofiles/samsung SM-G930V.dcp
Labels: scope: calibration

#6555 Fix for white outlines and background in AppImage
  .github/workflows/appimage.yml
Labels: scope: distribution

#6554 Remove the HISTOGRAM_TOOLTIP_RAW from all language files
  rtdata/languages/Catala
  rtdata/languages/Chinese (Simplified)
  rtdata/languages/Czech
  rtdata/languages/Deutsch
  rtdata/languages/English (UK)
  rtdata/languages/English (US)
  rtdata/languages/Espanol
  rtdata/languages/Francais
  rtdata/languages/Italiano
  rtdata/languages/Japanese
  rtdata/languages/Magyar
  rtdata/languages/Nederlands
  rtdata/languages/Polish
  rtdata/languages/Portugues
  rtdata/languages/Portugues (Brasil)
  rtdata/languages/Russian
  rtdata/languages/Serbian (Cyrilic Characters)
  rtdata/languages/Slovenian
  rtdata/languages/Swedish
  rtdata/languages/default
Labels: scope: localization

#6503 Add Japanese and Danish translations
  rtdata/languages/Dansk
  rtdata/languages/Japanese
Labels: scope: localization

#6550 Updated German translation
  rtdata/languages/Deutsch
Labels: scope: localization

#6547 Castellano (Spanish) language file
  AUTHORS.txt
  rtdata/languages/Espanol (Castellano)
  rtdata/languages/Espanol (Latin America)
  rtgui/multilangmgr.cc
  rtgui/options.cc
Labels: scope: localization

#6571 Fix for Nikon D5100 black image regression
  rtengine/dcraw.cc
Labels: type: bug, scope: file format

#6565 Update Chinese (Simplified) language file
  rtdata/languages/Chinese (Simplified)
Labels: scope: localization

#6570 Canon 1000D White Level Regression Fix
  rtengine/dcraw.cc
Labels: type: bug
