Repository RawTherapee/RawTherapee, pull requests merged in 2023-01, with the labels that each got.

#6655 Initial support for GX680 digital back
  rtdata/dcpprofiles/FUJIFILM DBP for GX680.dcp
  rtengine/camconst.json
  rtengine/dcraw.cc
  rtengine/dcraw.h
Labels: type: enhancement, scope: file format, scope: calibration

#6382 Support Dnggainmap for bayer files
  rtdata/languages/default
  rtengine/array2D.h
  rtengine/dcraw.cc
  rtengine/dcraw.h
  rtengine/dnggainmap.h
  rtengine/imagesource.h
  rtengine/improccoordinator.cc
  rtengine/procparams.cc
  rtengine/procparams.h
  rtengine/rawimage.h
  rtengine/rawimagesource.cc
  rtengine/rawimagesource.h
  rtengine/rtengine.h
  rtengine/stdimagesource.h
  rtgui/flatfield.cc
  rtgui/flatfield.h
  rtgui/paramsedited.cc
  rtgui/paramsedited.h
  rtgui/partialpastedlg.cc
  rtgui/partialpastedlg.h
  rtgui/toolpanelcoord.cc
  rtgui/toolpanelcoord.h
Labels: type: feature

#6299 Multiple External Editors
  rtdata/languages/default
  rtgui/CMakeLists.txt
  rtgui/editorpanel.cc
  rtgui/editorpanel.h
  rtgui/editwindow.cc
  rtgui/editwindow.h
  rtgui/externaleditorpreferences.cc
  rtgui/externaleditorpreferences.h
  rtgui/extprog.cc
  rtgui/extprog.h
  rtgui/guiutils.cc
  rtgui/guiutils.h
  rtgui/options.cc
  rtgui/options.h
  rtgui/popupcommon.cc
  rtgui/popupcommon.h
  rtgui/preferences.cc
  rtgui/preferences.h
  rtgui/rtappchooserdialog.cc
  rtgui/rtappchooserdialog.h
  rtgui/rtimage.cc
  rtgui/rtimage.h
  rtgui/rtwindow.cc
  rtgui/rtwindow.h
Labels: type: enhancement

#6672 Add libsharpyuv-0.dll to Windows build
  .github/workflows/windows.yml
Labels: scope: distribution
