Repository RawTherapee/RawTherapee, pull requests merged in 2023-08, with the labels that each got.

#6809 Fix external editor on macOS
  rtgui/editorpanel.cc
  rtgui/editorpanel.h
  rtgui/externaleditorpreferences.cc
  rtgui/extprog.cc
  rtgui/extprog.h
  rtgui/popupcommon.cc
  rtgui/popupcommon.h
  rtgui/preferences.cc
Labels: os: macOS

#6807 Fix PDAF lines pattern for Sony ILCE-7RM2
  rtengine/camconst.json
Labels: scope: calibration

#6789 Language names
  rtdata/languages/Catala
  rtdata/languages/Chinese (Simplified)
  rtdata/languages/Czech
  rtdata/languages/Dansk
  rtdata/languages/Deutsch
  rtdata/languages/Espanol (Castellano)
  rtdata/languages/Espanol (Latin America)
  rtdata/languages/Francais
  rtdata/languages/Italiano
  rtdata/languages/Japanese
  rtdata/languages/Magyar
  rtdata/languages/Nederlands
  rtdata/languages/Polish
  rtdata/languages/Portugues
  rtdata/languages/Portugues (Brasil)
  rtdata/languages/README
  rtdata/languages/Russian
  rtdata/languages/Serbian (Cyrilic Characters)
  rtdata/languages/Slovenian
  rtdata/languages/Swedish
  rtgui/multilangmgr.cc
  rtgui/multilangmgr.h
  rtgui/preferences.cc
Labels: scope: localization, scope: GUI

#6794 Fix for Auto-matched camera profile detection when using the English (US) language
  rtengine/dcp.cc
Labels: scope: calibration

#6808 Show favorite places at the top of the list
  rtdata/themes/RawTherapee - Legacy-GTK3-20_.css
  rtdata/themes/RawTherapee-GTK3-20_.css
  rtgui/placesbrowser.cc
Labels: type: enhancement, scope: GUI

#6820 Fix for Treeview's editable entries incorrectly displayed
  rtdata/themes/RawTherapee-GTK3-20_.css
Labels: type: bug, scope: GUI

#6755 Edit Lensfun database directory from preferences
  rtdata/languages/default
  rtgui/guiutils.cc
  rtgui/guiutils.h
  rtgui/preferences.cc
  rtgui/preferences.h
Labels: type: enhancement, scope: GUI

#6814 External editor button: synchronize in multiple editors layout
  rtgui/editwindow.cc
  rtgui/editwindow.h
  rtgui/popupcommon.cc
  rtgui/popupcommon.h
  rtgui/rtwindow.cc
  rtgui/rtwindow.h
Labels: scope: GUI

#6817 Use `_WIN32` instead of `WIN32` to detect Windows
  rtengine/dcraw.c
  rtengine/dcraw.cc
  rtengine/dcraw.h
  rtengine/dynamicprofile.cc
  rtengine/iccstore.cc
  rtengine/imagedata.cc
  rtengine/imageio.cc
  rtengine/jdatasrc.cc
  rtengine/lcp.cc
  rtengine/myfile.cc
  rtengine/mytime.h
  rtengine/procparams.cc
  rtengine/rawimage.cc
  rtengine/winutils.h
  rtgui/batchqueue.cc
  rtgui/batchqueueentry.cc
  rtgui/cachemanager.cc
  rtgui/cropwindow.cc
  rtgui/dirbrowser.cc
  rtgui/dirbrowser.h
  rtgui/editorpanel.cc
  rtgui/externaleditorpreferences.cc
  rtgui/extprog.cc
  rtgui/extprog.h
  rtgui/filebrowser.cc
  rtgui/filebrowser.h
  rtgui/filepanel.cc
  rtgui/icmpanel.cc
  rtgui/lensprofile.cc
  rtgui/main-cli.cc
  rtgui/main.cc
  rtgui/md5helper.h
  rtgui/multilangmgr.cc
  rtgui/navigator.cc
  rtgui/options.cc
  rtgui/options.h
  rtgui/pathutils.cc
  rtgui/placesbrowser.cc
  rtgui/preferences.cc
  rtgui/rtappchooserdialog.cc
  rtgui/rtwindow.cc
  rtgui/soundman.cc
  rtgui/threadutils.cc
  rtgui/thumbnail.cc
Labels: os: Windows
