Repository RawTherapee/RawTherapee, pull requests merged in 2024-12, with the labels that each got.

#7269 macOS CI: upgrades x86_64 runner to macOS 13
  .github/workflows/macos.yml
Labels: os: macOS, scope: distribution

#7249 Canon R8 electronic shutter black level fix
  rtengine/camconst.json
Labels: scope: calibration

#7254 Sony ILCE-7M3 (and other Sony cameras) black level
  rtengine/camconst.json
  rtengine/dcraw.cc
  rtengine/dcraw.h
Labels: scope: file format, scope: calibration

#7257 Compiler warning fixes
  rtengine/FTblockDN.cc
  rtengine/canon_cr3_decoder.cc
  rtengine/dcraw.cc
  rtengine/imagedata.cc
  rtengine/imageio.cc
  rtengine/iplocallab.cc
  rtengine/ipwavelet.cc
  rtengine/metadata.cc
  rtengine/rtthumbnail.cc
  rtgui/editorpanel.cc
  rtgui/main-cli.cc
  rtgui/main.cc
  rtgui/myflatcurve.cc
  rtgui/options.cc
  rtgui/profilestorecombobox.cc
  rtgui/rtimage.cc
  rtgui/rtscalable.cc
  rtgui/rtsurface.cc
  rtgui/thumbnail.cc
  rtgui/toolpanelcoord.cc
Labels: scope: compilation
