Repository RawTherapee/RawTherapee, pull requests merged in 2024-03, with the labels that each got.

#6959 mac: update codesign procedures
  tools/osx/macosx_bundle.sh
Labels: os: macOS, scope: distribution

#6952 Sony ILCE-7CR / ILCE-7RM5 camconst
  rtengine/camconst.json
Labels: scope: calibration

#6872 Implement maximal zoom feature
  rtdata/languages/default
  rtgui/cropwindow.cc
  rtgui/options.cc
  rtgui/options.h
  rtgui/preferences.cc
  rtgui/preferences.h
Labels: type: enhancement, scope: GUI

#6977 denoise gui: set luminance detail adjuster default as procparams default
  rtgui/dirpyrdenoise.cc
Labels: type: bug, scope: GUI

#6981 Update Dutch translation
  rtdata/languages/Nederlands
Labels: scope: localization

#6983 Read camera white balance for Canon EOS R6m2, R7, and more
  rtengine/dcraw.cc
Labels: type: bug

#7007 Fix Windows automated builds (Adwaita cursors)
  .github/workflows/windows.yml
Labels: scope: distribution, os: Windows

#6974 Italian translation
  rtdata/languages/Italiano
Labels: scope: localization

#6769 Recursive image browsing
  rtdata/icons/rawtherapee/scalable/apps/folder-subfolder.svg
  rtdata/languages/default
  rtgui/filecatalog.cc
  rtgui/filecatalog.h
  rtgui/options.cc
  rtgui/options.h
  rtgui/preferences.cc
  rtgui/preferences.h
Labels: type: enhancement, scope: GUI

#7003 Initial support for OM TG-7
  rtengine/camconst.json
  rtengine/dcraw.cc
Labels: scope: file format, scope: calibration

#6962 Read embedded dcp profile from raw files
  rtdata/languages/default
  rtengine/rawimagesource.cc
  rtengine/rawimagesource.h
  rtengine/rtthumbnail.cc
  rtgui/icmpanel.cc
  rtgui/icmpanel.h
Labels: type: enhancement, scope: color management

#7006 iplab2rgb: Fix memory leak
  rtengine/iplab2rgb.cc
Labels: type: bug

#7009 options: fix BrowseRecursiveFollowLinks reading
  rtgui/options.cc
Labels: scope: GUI
