Repository RawTherapee/RawTherapee, pull requests merged in 2024-11, with the labels that each got.

#7212 Support for images with more than 6 sub-frames
  rtengine/rawimagesource.cc
  rtengine/rawimagesource.h
  rtgui/bayerprocess.cc
Labels: scope: file format

#7178 Allow using more than 255 Edit Widgets for locallab
  rtgui/cropwindow.cc
  rtgui/editbuffer.cc
  rtgui/editwidgets.cc
  rtgui/editwidgets.h
Labels: scope: GUI

#7231 Ukrainian translation
  AUTHORS.txt
  rtdata/languages/Ukrainian
  rtgui/multilangmgr.cc
Labels: scope: localization

#7246 Include offset times in default EXIF tags
  rtengine/procparams.cc
Labels: scope: metadata
