Repository RawTherapee/RawTherapee, pull requests merged in 2024-01, with the labels that each got.

#6885 Fixes for memory leaks and memcpy overlap found by AddressSanitizer
  rtengine/imageio.cc
  rtgui/controlspotpanel.cc
  rtgui/controlspotpanel.h
  rtgui/locallab.cc
  rtgui/previewloader.cc
  rtgui/thumbimageupdater.cc
Labels: type: bug

#6894 AppImage workflow debug build
  .github/workflows/appimage.yml
Labels: scope: distribution, os: Linux

#6927 Panasonic DC-G100 white levels
  rtengine/camconst.json
Labels: scope: calibration

#6858 Add DCPs from ART
  rtdata/dcpprofiles/CANON EOS 250D.dcp
  rtdata/dcpprofiles/CANON EOS 800D.dcp
  rtdata/dcpprofiles/CANON EOS M50.dcp
  rtdata/dcpprofiles/CANON POWERSHOT G5 X MARK II.dcp
  rtdata/dcpprofiles/FUJIFILM X-A7.dcp
  rtdata/dcpprofiles/FUJIFILM X-E3.dcp
  rtdata/dcpprofiles/FUJIFILM X-S10.dcp
  rtdata/dcpprofiles/NIKON D3300.dcp
  rtdata/dcpprofiles/NIKON Z 5.dcp
  rtdata/dcpprofiles/NIKON Z 6_2.dcp
  rtdata/dcpprofiles/OLYMPUS E-M1.dcp
  rtdata/dcpprofiles/PANASONIC DMC-LX100.dcp
  rtdata/dcpprofiles/SONY DSC-RX100M6.dcp
  rtdata/dcpprofiles/SONY ILCE-7.dcp
  rtdata/dcpprofiles/SONY ILCE-7C.dcp
  rtdata/dcpprofiles/SONY ILCE-7SM3.dcp
  rtdata/dcpprofiles/camera_model_aliases.json
Labels: scope: color management

#6857 Update camconst.json from ART
  rtengine/camconst.json
Labels: scope: calibration

#6865 Fix camconst.json white levels for 1DxII
  rtengine/camconst.json
Labels: scope: calibration

#6935 Upgrade AppImage Exiv2 from v0.28.0 to v0.28.1
  .github/workflows/appimage.yml
Labels: scope: distribution, os: Linux
