Repository RawTherapee/RawTherapee, pull requests merged in 2024-08, with the labels that each got.

#7139 Mac: clarify installation instructions
  tools/osx/INSTALL.readme.rtf
  tools/osx/rtdmg-bkgd.png
Labels: os: macOS, scope: distribution

#7157 Update Chinese (Simplified) translation
  rtdata/languages/Chinese (Simplified)
Labels: scope: localization

#7158 Update Dutch translation
  rtdata/languages/Nederlands
Labels: scope: localization

#7168 Selective Editing icon
  rtdata/icons/rawtherapee/scalable/apps/rt-spot.svg
  rtgui/toolbar.cc
  rtgui/toolpanelcoord.cc
Labels: scope: GUI

#7174 Updated Dutch translation
  rtdata/languages/Nederlands
Labels: scope: localization

#7166 mac: CI/bundle update
  .github/workflows/macos.yml
  tools/osx/macosx_bundle.sh
  tools/osx/rtdmg-bkgd.png
Labels: os: macOS, scope: distribution

#7176 localisation deutsch 5.11
  rtdata/languages/Deutsch
Labels: scope: localization

#7182 Mac: update copyright year
  tools/osx/Info.plist.in
  tools/osx/rtdmg-bkgd.png
Labels: os: macOS
