Repository RawTherapee/RawTherapee, pull requests merged in 2024-07, with the labels that each got.

#7096 Enable extensions that are missing from config
  rtdata/languages/English (UK)
  rtdata/languages/English (US)
  rtdata/languages/default
  rtdata/options/options.lin
  rtdata/options/options.osx
  rtdata/options/options.win
  rtgui/options.cc
  rtgui/options.h
  rtgui/preferences.cc
  rtgui/preferences.h
Labels: type: enhancement

#7116 Mac: packaging fix for jxl
  .github/workflows/macos.yml
  tools/osx/macosx_bundle.sh
Labels: os: macOS, scope: distribution

#7100 Lens correction based on metadata (Sony, Fuji, Olympus, Panasonic, DNG)
  rtdata/languages/default
  rtengine/CMakeLists.txt
  rtengine/dcrop.cc
  rtengine/imagedata.cc
  rtengine/imagedata.h
  rtengine/improcfun.h
  rtengine/iptransform.cc
  rtengine/lcp.cc
  rtengine/lcp.h
  rtengine/lensmetadata.cc
  rtengine/lensmetadata.h
  rtengine/procparams.cc
  rtengine/procparams.h
  rtengine/rawimagesource.cc
  rtengine/rtengine.h
  rtengine/rtlensfun.cc
  rtengine/rtlensfun.h
  rtgui/cacheimagedata.cc
  rtgui/cacheimagedata.h
  rtgui/lensprofile.cc
  rtgui/lensprofile.h
Labels: type: feature

#7123 Improved generateTranslationDiffs script
  tools/generateTranslationDiffs.py
Labels: scope: localization

#7128 Language file updates for 5.11
  rtdata/languages/Catala
  rtdata/languages/Chinese (Simplified)
  rtdata/languages/Czech
  rtdata/languages/Dansk
  rtdata/languages/Deutsch
  rtdata/languages/English (UK)
  rtdata/languages/English (US)
  rtdata/languages/Espanol (Castellano)
  rtdata/languages/Espanol (Latin America)
  rtdata/languages/Francais
  rtdata/languages/Italiano
  rtdata/languages/Japanese
  rtdata/languages/Magyar
  rtdata/languages/Nederlands
  rtdata/languages/Polish
  rtdata/languages/Portugues
  rtdata/languages/Portugues (Brasil)
  rtdata/languages/Russian
  rtdata/languages/Serbian (Cyrilic Characters)
  rtdata/languages/Slovenian
  rtdata/languages/Swedish
  rtdata/languages/default
Labels: scope: localization

#7132 macOS CI: build for arm64
  .github/workflows/macos.yml
  tools/osx/macosx_bundle.sh
Labels: os: macOS, scope: distribution

#7141 DCPs and camconst.json entries from ART
  rtdata/dcpprofiles/NIKON Z 8.dcp
  rtdata/dcpprofiles/NIKON Z 9.dcp
  rtdata/dcpprofiles/NIKON Z F.dcp
  rtdata/dcpprofiles/camera_model_aliases.json
  rtengine/camconst.json
Labels: scope: calibration

#7142 AppImage exiv2 and libjxl upgrade
  .github/workflows/appimage.yml
  .github/workflows/codeql.yml
  tools/makedeb/PKGBUILD.libjxl
Labels: scope: distribution, os: Linux

#7144 Update Russian translation
  rtdata/languages/Russian
Labels: scope: localization
