Repository RawTherapee/RawTherapee, pull requests merged in 2024-06, with the labels that each got.

#7073 Add support for Panasonic DC-GH5M2
  rtengine/dcraw.cc
  rtengine/panasonic_decoders.cc
Labels: scope: file format

#7005 dcraw: handle Fujifilm lossy compression
  rtengine/dcraw.h
  rtengine/fujicompressed.cc
Labels: scope: file format

#7019 dcraw: add Panasonic DC-G9M2
  rtengine/dcraw.cc
Labels: scope: calibration

#7078 Update Chinese (Simplified) translation
  rtdata/languages/Chinese (Simplified)
Labels: scope: localization

#7018 Add Panasonic v8 decoder and support for DC-S5M2 and DC-S5M2X
  rtengine/dcraw.cc
  rtengine/dcraw.h
  rtengine/panasonic_decoders.cc
Labels: scope: file format

#6367 Add ability to import JXL images
  .github/workflows/appimage.yml
  .github/workflows/codeql.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  AboutThisBuild.txt.in
  CMakeLists.txt
  rtdata/languages/Catala
  rtdata/languages/Chinese (Simplified)
  rtdata/languages/Czech
  rtdata/languages/Dansk
  rtdata/languages/Deutsch
  rtdata/languages/English (UK)
  rtdata/languages/English (US)
  rtdata/languages/Espanol (Castellano)
  rtdata/languages/Espanol (Latin America)
  rtdata/languages/Francais
  rtdata/languages/Italiano
  rtdata/languages/Japanese
  rtdata/languages/Magyar
  rtdata/languages/Nederlands
  rtdata/languages/Polish
  rtdata/languages/Portugues
  rtdata/languages/Portugues (Brasil)
  rtdata/languages/Russian
  rtdata/languages/Serbian (Cyrilic Characters)
  rtdata/languages/Slovenian
  rtdata/languages/Swedish
  rtdata/languages/default
  rtdata/options/options.lin
  rtdata/options/options.osx
  rtdata/options/options.win
  rtengine/CMakeLists.txt
  rtengine/imageio.cc
  rtengine/imageio.h
  rtengine/stdimagesource.cc
  rtengine/utils.cc
  rtengine/utils.h
  rtgui/thumbnail.cc
  tools/makedeb/PKGBUILD.libjxl
Labels: scope: file format

#7091 Upgrade deprecated GitHub actions
  .github/workflows/appimage.yml
  .github/workflows/codeql.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: scope: distribution

#7092 Windows installer: Open images in existing RawTherapee window
  tools/win/InnoSetup/WindowsInnoSetup.iss.in
Labels: scope: distribution, os: Windows

#7086 Japanese translation update
  rtdata/languages/Japanese
Labels: scope: localization

#7098 adobe_coeff constants from LibRaw
  rtengine/dcraw.cc
Labels: scope: calibration

#7094 Fujifilm X-H2S color matrix and raw crop
  rtengine/camconst.json
Labels: scope: calibration

#7106 Nikon Z f color matrix
  rtengine/camconst.json
Labels: scope: calibration

#7105 Remove Itanium architecture support for Windows
  UpdateInfo.cmake
Labels: scope: distribution, os: Windows
