Repository RawTherapee/RawTherapee, pull requests merged in 2025-02, with the labels that each got.

#7274 Fix for Blur/Grain & Denoise in global mode
  rtengine/iplocallab.cc
Labels: tool: selective editing

#7281 Sony lens identification improvement
  rtengine/imagedata.cc
Labels: scope: metadata

#7265 Quick info font size
  rtgui/imagearea.cc
Labels: scope: GUI

#7296 Fix for artifact uploading from GitHub Actions
  .github/workflows/appimage.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: scope: distribution

#7298 Fix for macOS ARM build
  .github/workflows/macos.yml
Labels: scope: distribution

#7306 Chinese (Simplified) translation update
  rtdata/languages/Chinese (Simplified)
Labels: scope: localization

#7318 Lensfun automatic detection speedup
  rtengine/rtlensfun.cc
Labels: scope: performance

#7299 Fujifilm electronic shutter raw crop for dcraw
  rtengine/dcraw.cc
Labels: scope: file format

#7305 Directory browser performance improvement
  rtgui/dirbrowser.cc
Labels: scope: performance

#7276 Clean up framing compiler warnings
  rtengine/ipresize.cc
  rtgui/compressgamut.cc
  rtgui/framing.cc
  rtgui/framing.h
  rtgui/toolpanelcoord.cc
Labels: scope: compilation
