Repository RawTherapee/RawTherapee, pull requests merged in 2025-06, with the labels that each got.

#7292 Format in output template
  rtdata/languages/default
  rtgui/batchqueue.cc
  rtgui/batchqueue.h
  rtgui/batchqueuepanel.cc
Labels: type: enhancement

#7403 macos: touch the dmg background message file
  tools/osx/macosx_bundle.sh
Labels: os: macOS, scope: distribution

#7266 Embedded XMP color label support
  rtengine/imagedata.cc
  rtengine/imagedata.h
  rtengine/rtengine.h
  rtgui/cacheimagedata.cc
  rtgui/cacheimagedata.h
  rtgui/thumbnail.cc
Labels: type: enhancement, scope: metadata

#7280 Add sliders for scaling images horizontally or vertically only
  rtdata/languages/default
  rtengine/dcrop.cc
  rtengine/dcrop.h
  rtengine/improcfun.h
  rtengine/iptransform.cc
  rtengine/perspectivecorrection.cc
  rtengine/procparams.cc
  rtengine/procparams.h
  rtgui/addsetids.h
  rtgui/lensgeom.cc
  rtgui/lensgeom.h
  rtgui/paramsedited.cc
  rtgui/paramsedited.h
  rtgui/preferences.cc
Labels: type: feature
