Repository RawTherapee/RawTherapee, pull requests merged in 2025-04, with the labels that each got.

#7339 New color matrices and DCP
  rtdata/cammatrices.json
  rtdata/dcpprofiles/PANASONIC DC-S5M2.dcp
Labels: scope: calibration

#7350 AppImage workflow fix
  .github/workflows/appimage.yml
  tools/makedeb/PKGBUILD.libjxl
Labels: scope: distribution, os: Linux

#7346 Fix for Nikon D5 black level when using LibRaw
  rtengine/camconst.json
Labels: scope: calibration

#7351 localisation deutsch
  rtdata/languages/Deutsch
Labels: scope: localization

#7353 GHS tool panel width fix
  rtgui/locallabtools.cc
Labels: scope: GUI

#7364 Chinese (Simplified) translation update
  rtdata/languages/Chinese (Simplified)
Labels: scope: localization

#7366 Dutch translation update
  rtdata/languages/Nederlands
Labels: scope: localization
