Repository RawTherapee/RawTherapee, pull requests merged in 2025-05, with the labels that each got.

#7375 Fix for some images being too bright when using LibRaw
  rtengine/rawimage.cc
Labels: scope: file format

#7398 macOS: update bundle jxl-cms handler
  tools/osx/macosx_bundle.sh
Labels: os: macOS, scope: distribution

#7397 Remove benchmarking
  rtengine/hilite_recon.cc
  rtengine/iplocallab.cc
  rtengine/ipretinex.cc
  rtengine/ipwavelet.cc
  rtengine/rawimagesource.cc
Labels: scope: performance

#7407 Fix for profiled lens correction with manually selected lens
  rtengine/rtlensfun.cc
Labels: type: bug
