Repository RawTherapee/RawTherapee, pull requests merged in 2025-01, with the labels that each got.

#7245 Separation of camconst files
  rtdata/CMakeLists.txt
  rtdata/cammatrices.json
  rtdata/dcraw.json
  rtdata/rt.json
  rtengine/camconst.cc
  tools/update_camconst.py
Labels: type: enhancement, scope: calibration

#7259 Raw dehaze negative values fix
  rtengine/rawimagesource.cc
Labels: type: enhancement

#7264 Demosaiced floating point DNGs
  rtengine/rawimage.cc
  rtengine/rawimage.h
  rtengine/rtthumbnail.cc
Labels: scope: file format

#7111 Abstract Profile - Contrast enhancement -- Selective Editing Cam16 and JzCzHz - improvments
  rtdata/languages/default
  rtengine/cplx_wavelet_dec.h
  rtengine/cplx_wavelet_filter_coeffs.h
  rtengine/dcrop.cc
  rtengine/improccoordinator.cc
  rtengine/improccoordinator.h
  rtengine/improcfun.cc
  rtengine/improcfun.h
  rtengine/iplocallab.cc
  rtengine/ipwavelet.cc
  rtengine/procevents.h
  rtengine/procparams.cc
  rtengine/procparams.h
  rtengine/refreshmap.cc
  rtengine/rtengine.h
  rtengine/rtthumbnail.cc
  rtengine/simpleprocess.cc
  rtgui/colorappearance.cc
  rtgui/controlspotpanel.cc
  rtgui/icmpanel.cc
  rtgui/icmpanel.h
  rtgui/locallab.cc
  rtgui/locallabtools.cc
  rtgui/locallabtools.h
  rtgui/locallabtools2.cc
  rtgui/options.cc
  rtgui/options.h
  rtgui/paramsedited.cc
  rtgui/paramsedited.h
  rtgui/wavelet.cc
Labels: type: enhancement
